apiVersion : apps/v1
kind: Deployment
metadata:
  name: albaferridummyvulnapp 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: albaferridummyvulnapp
  template:
    metadata:
      labels:
        app: albaferridummyvulnapp 
    spec:
      containers:
        - name: albaferridummyvulnapp 
          image: alejandroregistry.azurecr.io/azure-pipelines-dummyvulnapp:135
          ports:
          - containerPort: 5000
